"""Baseline migration - represents the initial schema state of all existing SQLAlchemy models.

This is intentionally a no-op because the database schema already exists
(created by Supabase or prior manual setup). Future migrations will be
autogenerated diffs against the current model definitions.

Revision ID: 0001_baseline
Revises: None
Create Date: 2026-03-05

"""
from typing import Sequence, Union

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Baseline -- no-op. Schema already exists."""
    pass


def downgrade() -> None:
    """Baseline -- no-op. Cannot downgrade past initial state."""
    pass
